# Permalinks
permalink:      /:year/:month/:day/:title

# Setup
title:          Radhika Morabia &#8212; Frontend Web Developer
paginate:       10
baseurl:        ""
url:            "http://rmorabia.com"
paginate_path:  "/log/page/:num/"

# Build settings
markdown:       kramdown
highlighter:    rouge

kramdown:
  input: GFM

# About
name: Radhika Morabia
url: http://rmorabia.com
email: hi@rmorabia.com
description: Radhika Morabia is a frontend web developer specializing in React and JavaScript.

# Gems
plugins-dir:
  - jekyll-paginate
gems: [jekyll-paginate]

plugins:
  - jekyll-feed