# Permalinks
permalink:      /:year/:month/:day/:title

# Setup
title:          Radhika Morabia &#8212; Aspiring JavaScript Developer
paginate:       10
baseurl:        ""
url:            "http://rmorabia.com"
paginate_path:  "/log/page/:num/"

# Build settings
markdown:       kramdown
highlighter:    rouge

# About
#  name:         Radhika Morabia
#  url:          http://rmorabia.com
#  email:        hi@rmorabia.com

# Gems
plugins-dir:
  - jekyll-paginate
  - jekyll-feed
gems: [jekyll-paginate]
