# Permalinks
permalink:      /:year/:month/:day/:title

# Setup
title:          Radhika Morabia
paginate:       5
baseurl:        ""
url:            "http://rmorabia.com"
paginate_path:  "/log/page:num/"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
# author:
#  name:         Radhika Morabia
#  url:          http://rmorabia.com
#  email:        hi@rmorabia.com

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/chesterhow/tale

# Gems
plugins-dir:
  - jekyll-paginate
gems: [jekyll-paginate]
